### ISSUE TITLE
Error : TypeError: urlToHttpOptions is not a function when running in Heroku

### ISSUE THREAD

**Issue by draeder** [theobarrague/fake-bittorrent-client#3]
I built a [tracker swarm module](https://www.npmjs.com/package/tracker-swarm) that works great locally when using fake-bittorrent-client to test tracker servers. However, when running fake-bittorrent-client in Heroku, I get this error:

```
Error : TypeError: urlToHttpOptions is not a function when running in Heroku
```

Any ideas why this might be happening?

**Comment by draeder** [comment]
I think the issue is here in FakeBittorrentClient.ts:

```
//var options = urlToHttpOptions(new URL(url)); <-- Change this
var options = new URL(url) //<-- To this
```

I've tested without `urlToHttpOptions` and just `new URL(url)` and it still works fine. Since I'm using `new URL()` in my module successfully in Heroku, I believe this will fix it.

I'll submit a PR.

**Comment by draeder** [comment]
Well, it looks like I can't submit a PR for this repo.

**Comment by theobarrague** [comment]
Nice, thank's you :)
